# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

#[[main]]
#  name = "Home"
#  url = "/"
#  weight = 10

#[[main]]
#  name = "Home"
#  url = "post"
#  weight = 20

[[main]]
  name = "Home"
  url = "/"
  weight = 30

[[main]]
  name = "Work"
  url = "working"
  weight = 40

[[main]]
  name = "Interests"
  url = "interests"
  weight = 50

[[main]]
  name = "Contact"
  url = "contact"
  weight = 60
